{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-prod\"} | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(get_total[30s])", "legendFormat": "get" },
    { "expr": "rate(put_total[30s])", "legendFormat": "put" },
    { "expr": "rate(post_total[30s])", "legendFormat": "post" },
    { "expr": "rate(delete_total[30s])", "legendFormat": "delete" }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(delete_latency_milliseconds_total[30s])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(put_latency_milliseconds_total[30s])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(post_latency_milliseconds_total[30s])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(get_latency_milliseconds_total[30s])",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "cpu" },
    { "expr": "memory_percent", "legendFormat": "memory" }
   ]
  }
 ]
}